// Generated by CoffeeScript 1.4.0
(function() {
  var BaseModel, mongoose;

  mongoose = require("mongoose");

  module.exports = BaseModel = (function() {

    function BaseModel(modelName, collection, schema, props) {
      this.modelName = modelName;
      this.collection = collection;
      this.schema = schema;
      this.dbModel = mongoose.model(this.modelName, this.schema, this.collection);
      this.model = new this.dbModel(props);
      this.schema.virtual('id').get(function() {
        return this._id;
      });
      this.schema.methods.toBackbone = function() {
        var obj;
        obj = this.toObject();
        obj.id = obj._id;
        return obj;
      };
    }

    BaseModel.prototype.getModelName = function() {
      return this.modelName;
    };

    BaseModel.prototype.getDBModel = function() {
      return this.dbModel;
    };

    BaseModel.prototype.getDBSchema = function() {
      return this.schema;
    };

    BaseModel.prototype.save = function() {
      return this.model.save();
    };

    return BaseModel;

  })();

}).call(this);
