// Generated by CoffeeScript 1.4.0
(function() {
  var BaseModel, mongoose;

  mongoose = require("mongoose");

  module.exports = BaseModel = (function() {

    function BaseModel(modelName, collection, schemaJSON, props) {
      this.modelName = modelName;
      this.collection = collection;
      if (props.winston !== void 0) {
        props.winston.info("BaseModel: " + this.modelName + " - " + this.collection, schemaJSON);
      }
      this.schema = new mongoose.Schema(schemaJSON);
      this.dbModel = mongoose.model(this.modelName, this.schema, this.collection);
      if (props.doc !== void 0) {
        this.model = new this.dbModel(props.doc);
      } else {
        this.model = new this.dbModel();
      }
      this.schema.virtual('id').get(function() {
        return this._id;
      });
      this.schema.methods.toBackbone = function() {
        var obj;
        obj = this.toObject();
        obj.id = obj._id;
        return obj;
      };
    }

    BaseModel.prototype.getModelName = function() {
      return this.modelName;
    };

    BaseModel.prototype.getCollection = function() {
      return this.collection;
    };

    BaseModel.prototype.getDBModel = function() {
      return this.dbModel;
    };

    BaseModel.prototype.getDBSchema = function() {
      return this.schema;
    };

    BaseModel.prototype.save = function() {
      return this.model.save();
    };

    return BaseModel;

  })();

}).call(this);
